use crate::android::backend::{
    input::{
        RelativePosition, WinitInput, WinitKeyboardInputEvent, WinitMouseInputEvent,
        WinitMouseMovedEvent, WinitMouseWheelEvent, WinitTouchEndedEvent,
        WinitTouchMovedEvent, WinitTouchStartedEvent,
    },
    keymap::physicalkey_to_scancode,
    WaylandBackend,
};
use smithay::backend::input::InputEvent;
use smithay::utils::{Physical, Size};
use winit::event::{ButtonSource, ElementState, PointerSource, WindowEvent};

/// Specific events generated by Winit
#[derive(Debug)]
pub enum CentralizedEvent {
    /// The window has been resized
    Resized {
        /// The new physical size (in pixels)
        size: Size<i32, Physical>,
        /// The new scale factor
        scale_factor: f64,
    },

    /// The focus state of the window changed
    Focus(bool),

    /// An input event occurred.
    Input(InputEvent<WinitInput>),

    /// The user requested to close the window.
    CloseRequested,

    /// A redraw was requested
    Redraw,

    /// TODO: Support these events
    Unsupported,
}

pub fn centralize(event: WindowEvent, backend: &mut WaylandBackend) -> CentralizedEvent {
    let time = backend.clock.now().as_millis() as u64;
    return match event {
        WindowEvent::SurfaceResized(size) => {
            let (w, h): (i32, i32) = size.into();

            CentralizedEvent::Resized {
                size: (w, h).into(),
                scale_factor: backend.scale_factor,
            }
        }
        WindowEvent::ScaleFactorChanged {
            scale_factor: new_scale_factor,
            ..
        } => {
            backend.scale_factor = new_scale_factor;
            let (w, h): (i32, i32) = backend
                .graphic_renderer
                .as_ref()
                .unwrap()
                .window()
                .surface_size()
                .into();
            CentralizedEvent::Resized {
                size: (w, h).into(),
                scale_factor: backend.scale_factor,
            }
        }
        WindowEvent::RedrawRequested => CentralizedEvent::Redraw,
        WindowEvent::CloseRequested => CentralizedEvent::CloseRequested,
        WindowEvent::Focused(focused) => CentralizedEvent::Focus(focused),
        WindowEvent::KeyboardInput {
            event,
            is_synthetic,
            ..
        } if !is_synthetic && !event.repeat => {
            match event.state {
                ElementState::Pressed => backend.key_counter += 1,
                ElementState::Released => {
                    backend.key_counter = backend.key_counter.saturating_sub(1);
                }
            };

            let scancode = physicalkey_to_scancode(event.physical_key).unwrap_or(0);
            let event = InputEvent::Keyboard {
                event: WinitKeyboardInputEvent {
                    time,
                    key: scancode,
                    count: backend.key_counter,
                    state: event.state,
                },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::PointerMoved {
            position, source, ..
        } => {
            let size = backend
                .graphic_renderer
                .as_ref()
                .unwrap()
                .window()
                .surface_size();
            let x = position.x / size.width as f64;
            let y = position.y / size.height as f64;
            match source {
                PointerSource::Touch { finger_id, .. } => {
                    CentralizedEvent::Input(InputEvent::TouchMotion {
                        event: WinitTouchMovedEvent {
                            time,
                            position: RelativePosition::new(x, y),
                            global_position: position,
                            id: finger_id.into_raw() as u64,
                        },
                    })
                }
                _ => {
                    CentralizedEvent::Input(InputEvent::PointerMotionAbsolute {
                        event: WinitMouseMovedEvent {
                            time,
                            position: RelativePosition::new(x, y),
                            global_position: position,
                        },
                    })
                }
            }
        }
        WindowEvent::MouseWheel { delta, .. } => {
            let event = InputEvent::PointerAxis {
                event: WinitMouseWheelEvent { time, delta },
            };
            CentralizedEvent::Input(event)
        }
        WindowEvent::PointerButton {
            state,
            button,
            position,
            ..
        } => match button {
            ButtonSource::Touch { finger_id, .. } => match state {
                ElementState::Pressed => {
                    let size = backend
                        .graphic_renderer
                        .as_ref()
                        .unwrap()
                        .window()
                        .surface_size();
                    let x = position.x / size.width as f64;
                    let y = position.y / size.height as f64;
                    CentralizedEvent::Input(InputEvent::TouchDown {
                        event: WinitTouchStartedEvent {
                            time,
                            global_position: position,
                            position: RelativePosition::new(x, y),
                            id: finger_id.into_raw() as u64,
                        },
                    })
                }
                ElementState::Released => {
                    CentralizedEvent::Input(InputEvent::TouchUp {
                        event: WinitTouchEndedEvent {
                            time,
                            id: finger_id.into_raw() as u64,
                        },
                    })
                }
            },
            ButtonSource::Mouse(mouse_button) => {
                CentralizedEvent::Input(InputEvent::PointerButton {
                    event: WinitMouseInputEvent {
                        time,
                        button: mouse_button,
                        state,
                        is_x11: false,
                    },
                })
            }
            _ => CentralizedEvent::Unsupported,
        },

        _ => {
            log::info!("Unhandled event: {:?}", event);
            CentralizedEvent::Unsupported
        }
    };
}
